export default [
    { 
     "profilephoto": "https://bootdey.com/img/Content/avatar/avatar5.png", 
      "occupation":"user occupation",
      "_id": "123",
      "about": "user profile description", 
      "website":"user website",  
      "location":"user location",  
      "companyname":"user compay name",
      "position":"user work position",
      "followers": 3,     
      "following": 2,    
      "liked": true ,    
      "likes":  5 ,    
      "posts": "reviews on past orders if any",   
      "phone":"user's phone number", 
      "username":"hari",   
      "firstName":"user's first name",   
      "lastName":"user's last name",    
      "email":"user's email",   
      "role":"CUSTOMER",
      "password":"password",
      "dateofbirth":"user's date of birth", 
      "dateofjoining":"user date of joining",   
      "previousorders": "number of previous orders",    
      "favorites": "favorite food places marked by the user",   
      "previousorderslist": "", 
      "favoriteslist": "array" 
    } ,
    { 
      "profilephoto": "https://bootdey.com/img/Content/avatar/avatar5.png", 
      "occupation":"user occupation",
      "_id": "345",
      "about": "user profile description", 
      "website":"user website",  
      "location":"user location",  
      "companyname":"user compay name",
      "position":"user work position",
      "followers": 3,     
      "following": 2,    
      "liked": true ,    
      "likes":  5 ,    
      "posts": "reviews on past orders if any",   
      "phone":"user's phone number",    
      "username":"hari1",   
      "firstName":"user's first name",   
      "lastName":"user's last name",    
      "email":"user's email",   
      "role":"DONOR",
      "password":"password", 
      "dateofbirth":"user's date of birth", 
      "dateofjoining":"user date of joining",   
      "previousorders": "number of previous orders",    
      "favorites": "favorite food places marked by the user",   
      "previousorderslist": "", 
      "favoriteslist": "array" 
    } 
]
  
  